### ISSUE TITLE
aoihttp 3.10.0 breaks helios

### ISSUE THREAD

**Issue by oscar1** [Stuub/Helios#4]
└─$ python3 helios.py --help
Traceback (most recent call last):
  File "/home/xxxxxx/helios/Helios/helios.py", line 44, in <module>
    session = aiohttp.ClientSession()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxxxx/helios/lib/python3.11/site-packages/aiohttp/client.py", line 296, in __init__
    loop = loop or asyncio.get_running_loop()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

Put aiohttp==3.9.5 in requirements.txt to fix (but code review would prob be better).

(and sorry about the typo in the title)

**Comment by Stuub** [comment]
Thanks a bunch for pointing this out! I'm on 3.9.5 myself, believe this must've been a cause of the recent merge :s 
Will amend and close now, gratzi <3
